// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxmzhetsyvjeshfphuyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bXpoZXRzeXZqZXNoZnBodXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTk0NDcsImV4cCI6MjA2Mzg5NTQ0N30.Cme7DlEhyMxIzW8-UlLclF0XvNfUUYUQven0-YFrEAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);